"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.Unload = exports.SneakCaptureCity = exports.SneakAttack = exports.Sleep = exports.PlantForest = exports.Pillage = exports.NoOrders = exports.Move = exports.FoundCity = exports.Fortify = exports.Embark = exports.Disembark = exports.Disband = exports.ClearSwamp = exports.ClearJungle = exports.ClearForest = exports.CaptureCity = exports.BuildRailroad = exports.BuildRoad = exports.BuildMine = exports.BuildIrrigation = exports.Attack = void 0;
var Actions_1 = require("@civ-clone/library-unit/Actions");
Object.defineProperty(exports, "Attack", { enumerable: true, get: function () { return Actions_1.Attack; } });
Object.defineProperty(exports, "BuildIrrigation", { enumerable: true, get: function () { return Actions_1.BuildIrrigation; } });
Object.defineProperty(exports, "BuildMine", { enumerable: true, get: function () { return Actions_1.BuildMine; } });
Object.defineProperty(exports, "BuildRoad", { enumerable: true, get: function () { return Actions_1.BuildRoad; } });
Object.defineProperty(exports, "BuildRailroad", { enumerable: true, get: function () { return Actions_1.BuildRailroad; } });
Object.defineProperty(exports, "CaptureCity", { enumerable: true, get: function () { return Actions_1.CaptureCity; } });
Object.defineProperty(exports, "ClearForest", { enumerable: true, get: function () { return Actions_1.ClearForest; } });
Object.defineProperty(exports, "ClearJungle", { enumerable: true, get: function () { return Actions_1.ClearJungle; } });
Object.defineProperty(exports, "ClearSwamp", { enumerable: true, get: function () { return Actions_1.ClearSwamp; } });
Object.defineProperty(exports, "Disband", { enumerable: true, get: function () { return Actions_1.Disband; } });
Object.defineProperty(exports, "Disembark", { enumerable: true, get: function () { return Actions_1.Disembark; } });
Object.defineProperty(exports, "Embark", { enumerable: true, get: function () { return Actions_1.Embark; } });
Object.defineProperty(exports, "Fortify", { enumerable: true, get: function () { return Actions_1.Fortify; } });
Object.defineProperty(exports, "FoundCity", { enumerable: true, get: function () { return Actions_1.FoundCity; } });
Object.defineProperty(exports, "Move", { enumerable: true, get: function () { return Actions_1.Move; } });
Object.defineProperty(exports, "NoOrders", { enumerable: true, get: function () { return Actions_1.NoOrders; } });
Object.defineProperty(exports, "Pillage", { enumerable: true, get: function () { return Actions_1.Pillage; } });
Object.defineProperty(exports, "PlantForest", { enumerable: true, get: function () { return Actions_1.PlantForest; } });
Object.defineProperty(exports, "Sleep", { enumerable: true, get: function () { return Actions_1.Sleep; } });
Object.defineProperty(exports, "SneakAttack", { enumerable: true, get: function () { return Actions_1.SneakAttack; } });
Object.defineProperty(exports, "SneakCaptureCity", { enumerable: true, get: function () { return Actions_1.SneakCaptureCity; } });
Object.defineProperty(exports, "Unload", { enumerable: true, get: function () { return Actions_1.Unload; } });
//# sourceMappingURL=Actions.js.map