"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.Unload = exports.Sleep = exports.PlantForest = exports.Pillage = exports.NoOrders = exports.Move = exports.FoundCity = exports.Fortify = exports.Embark = exports.Disembark = exports.Disband = exports.ClearSwamp = exports.ClearJungle = exports.ClearForest = exports.CaptureCity = exports.BuildRailroad = exports.BuildRoad = exports.BuildMine = exports.BuildIrrigation = exports.Attack = void 0;
var Attack_1 = require("@civ-clone/base-unit-action-attack/Attack");
Object.defineProperty(exports, "Attack", { enumerable: true, get: function () { return Attack_1.Attack; } });
var BuildIrrigation_1 = require("@civ-clone/base-unit-action-build-irrigation/BuildIrrigation");
Object.defineProperty(exports, "BuildIrrigation", { enumerable: true, get: function () { return BuildIrrigation_1.BuildIrrigation; } });
var BuildMine_1 = require("@civ-clone/base-unit-action-build-mine/BuildMine");
Object.defineProperty(exports, "BuildMine", { enumerable: true, get: function () { return BuildMine_1.BuildMine; } });
var BuildRoad_1 = require("@civ-clone/base-unit-action-build-road/BuildRoad");
Object.defineProperty(exports, "BuildRoad", { enumerable: true, get: function () { return BuildRoad_1.BuildRoad; } });
var BuildRailroad_1 = require("@civ-clone/base-unit-action-build-railroad/BuildRailroad");
Object.defineProperty(exports, "BuildRailroad", { enumerable: true, get: function () { return BuildRailroad_1.BuildRailroad; } });
var CaptureCity_1 = require("@civ-clone/base-unit-action-capture-city/CaptureCity");
Object.defineProperty(exports, "CaptureCity", { enumerable: true, get: function () { return CaptureCity_1.CaptureCity; } });
var ClearForest_1 = require("@civ-clone/base-unit-action-clear-forest/ClearForest");
Object.defineProperty(exports, "ClearForest", { enumerable: true, get: function () { return ClearForest_1.ClearForest; } });
var ClearJungle_1 = require("@civ-clone/base-unit-action-clear-jungle/ClearJungle");
Object.defineProperty(exports, "ClearJungle", { enumerable: true, get: function () { return ClearJungle_1.ClearJungle; } });
var ClearSwamp_1 = require("@civ-clone/base-unit-action-clear-swamp/ClearSwamp");
Object.defineProperty(exports, "ClearSwamp", { enumerable: true, get: function () { return ClearSwamp_1.ClearSwamp; } });
var Disband_1 = require("@civ-clone/base-unit-action-disband/Disband");
Object.defineProperty(exports, "Disband", { enumerable: true, get: function () { return Disband_1.Disband; } });
var Disembark_1 = require("@civ-clone/base-unit-action-disembark/Disembark");
Object.defineProperty(exports, "Disembark", { enumerable: true, get: function () { return Disembark_1.Disembark; } });
var Embark_1 = require("@civ-clone/base-unit-action-embark/Embark");
Object.defineProperty(exports, "Embark", { enumerable: true, get: function () { return Embark_1.Embark; } });
var Fortify_1 = require("@civ-clone/base-unit-action-fortify/Fortify");
Object.defineProperty(exports, "Fortify", { enumerable: true, get: function () { return Fortify_1.Fortify; } });
var FoundCity_1 = require("@civ-clone/base-unit-action-found-city/FoundCity");
Object.defineProperty(exports, "FoundCity", { enumerable: true, get: function () { return FoundCity_1.FoundCity; } });
var Move_1 = require("@civ-clone/base-unit-action-move/Move");
Object.defineProperty(exports, "Move", { enumerable: true, get: function () { return Move_1.Move; } });
var NoOrders_1 = require("@civ-clone/base-unit-action-no-orders/NoOrders");
Object.defineProperty(exports, "NoOrders", { enumerable: true, get: function () { return NoOrders_1.NoOrders; } });
var Pillage_1 = require("@civ-clone/base-unit-action-pillage/Pillage");
Object.defineProperty(exports, "Pillage", { enumerable: true, get: function () { return Pillage_1.Pillage; } });
var PlantForest_1 = require("@civ-clone/base-unit-action-plant-forest/PlantForest");
Object.defineProperty(exports, "PlantForest", { enumerable: true, get: function () { return PlantForest_1.PlantForest; } });
var Sleep_1 = require("@civ-clone/base-unit-action-sleep/Sleep");
Object.defineProperty(exports, "Sleep", { enumerable: true, get: function () { return Sleep_1.Sleep; } });
var Unload_1 = require("@civ-clone/base-unit-action-unload/Unload");
Object.defineProperty(exports, "Unload", { enumerable: true, get: function () { return Unload_1.Unload; } });
//# sourceMappingURL=Actions.js.map