import {
  Artillery,
  Battleship,
  Bomber,
  Cannon,
  Caravan,
  Carrier,
  Catapult,
  Chariot,
  Cruiser,
  Diplomat,
  Fighter,
  Frigate,
  Horseman,
  Ironclad,
  Knight,
  MechanizedInfantry,
  Musketman,
  Nuclear,
  Rifleman,
  Sail,
  Settlers,
  Spearman,
  Submarine,
  Swordman,
  Tank,
  Transport,
  Trireme,
  Warrior,
} from './Units';
import { instance as availableCityBuildItemsRegistryInstance } from '@civ-clone/core-city-build/AvailableCityBuildItemsRegistry';
import Buildable from '@civ-clone/core-city-build/Buildable';

availableCityBuildItemsRegistryInstance.register(
  ...([
    Artillery,
    Battleship,
    Bomber,
    Cannon,
    Caravan,
    Carrier,
    Catapult,
    Chariot,
    Cruiser,
    Diplomat,
    Fighter,
    Frigate,
    Horseman,
    Ironclad,
    Knight,
    MechanizedInfantry,
    Musketman,
    Nuclear,
    Rifleman,
    Sail,
    Settlers,
    Spearman,
    Submarine,
    Swordman,
    Tank,
    Transport,
    Trireme,
    Warrior,
  ] as unknown as typeof Buildable[])
);
