"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.Warrior = exports.Trireme = exports.Transport = exports.Tank = exports.Swordman = exports.Submarine = exports.Spearman = exports.Settlers = exports.Sail = exports.Rifleman = exports.Nuclear = exports.Musketman = exports.MechanizedInfantry = exports.Knight = exports.Ironclad = exports.Horseman = exports.Frigate = exports.Fighter = exports.Diplomat = exports.Cruiser = exports.Chariot = exports.Catapult = exports.Carrier = exports.Caravan = exports.Cannon = exports.Bomber = exports.Battleship = exports.Artillery = void 0;
var Units_1 = require("@civ-clone/library-unit/Units");
Object.defineProperty(exports, "Artillery", { enumerable: true, get: function () { return Units_1.Artillery; } });
Object.defineProperty(exports, "Battleship", { enumerable: true, get: function () { return Units_1.Battleship; } });
Object.defineProperty(exports, "Bomber", { enumerable: true, get: function () { return Units_1.Bomber; } });
Object.defineProperty(exports, "Cannon", { enumerable: true, get: function () { return Units_1.Cannon; } });
Object.defineProperty(exports, "Caravan", { enumerable: true, get: function () { return Units_1.Caravan; } });
Object.defineProperty(exports, "Carrier", { enumerable: true, get: function () { return Units_1.Carrier; } });
Object.defineProperty(exports, "Catapult", { enumerable: true, get: function () { return Units_1.Catapult; } });
Object.defineProperty(exports, "Chariot", { enumerable: true, get: function () { return Units_1.Chariot; } });
Object.defineProperty(exports, "Cruiser", { enumerable: true, get: function () { return Units_1.Cruiser; } });
Object.defineProperty(exports, "Diplomat", { enumerable: true, get: function () { return Units_1.Diplomat; } });
Object.defineProperty(exports, "Fighter", { enumerable: true, get: function () { return Units_1.Fighter; } });
Object.defineProperty(exports, "Frigate", { enumerable: true, get: function () { return Units_1.Frigate; } });
Object.defineProperty(exports, "Horseman", { enumerable: true, get: function () { return Units_1.Horseman; } });
Object.defineProperty(exports, "Ironclad", { enumerable: true, get: function () { return Units_1.Ironclad; } });
Object.defineProperty(exports, "Knight", { enumerable: true, get: function () { return Units_1.Knight; } });
Object.defineProperty(exports, "MechanizedInfantry", { enumerable: true, get: function () { return Units_1.MechanizedInfantry; } });
Object.defineProperty(exports, "Musketman", { enumerable: true, get: function () { return Units_1.Musketman; } });
Object.defineProperty(exports, "Nuclear", { enumerable: true, get: function () { return Units_1.Nuclear; } });
Object.defineProperty(exports, "Rifleman", { enumerable: true, get: function () { return Units_1.Rifleman; } });
Object.defineProperty(exports, "Sail", { enumerable: true, get: function () { return Units_1.Sail; } });
Object.defineProperty(exports, "Settlers", { enumerable: true, get: function () { return Units_1.Settlers; } });
Object.defineProperty(exports, "Spearman", { enumerable: true, get: function () { return Units_1.Spearman; } });
Object.defineProperty(exports, "Submarine", { enumerable: true, get: function () { return Units_1.Submarine; } });
Object.defineProperty(exports, "Swordman", { enumerable: true, get: function () { return Units_1.Swordman; } });
Object.defineProperty(exports, "Tank", { enumerable: true, get: function () { return Units_1.Tank; } });
Object.defineProperty(exports, "Transport", { enumerable: true, get: function () { return Units_1.Transport; } });
Object.defineProperty(exports, "Trireme", { enumerable: true, get: function () { return Units_1.Trireme; } });
Object.defineProperty(exports, "Warrior", { enumerable: true, get: function () { return Units_1.Warrior; } });
//# sourceMappingURL=Units.js.map